In [2]:
import numpy as np
dirs = ['R', 'D', 'L', 'U']

dir_step = {
    'R': [1, 0],
    'D': [0, 1],
    'L': [-1, 0],
    'U': [0, -1]
}
seen = {}

def print_spiral(arr):
    size = arr.shape[0]  
    num_printed = 0
    i = j = 0
    dir_idx = 0
    print arr[i][j]
    num_printed += 1
    seen[(i, j)] = True
    while num_printed < size * size:
        new_i, new_j, valid = get_next_child(i, j, dirs[dir_idx], size)
        if valid:
            i, j = new_i, new_j
            print arr[j][i]
            num_printed += 1
            seen[(new_i, new_j)] = True
            #print 'next index: (%d, %d)' % (new_i, new_j)
        else:
            dir_idx = (dir_idx + 1) % 4
            
def is_in_range(i, j, size):
    return (0 <= i <= size - 1) and (0 <= j <= size - 1)
            
def get_next_child(i, j, direc, size):
    new_i, new_j = np.add([i, j], dir_step[direc])
    in_range = is_in_range(new_i, new_j, size)
    if in_range and (new_i, new_j) not in seen:
        return new_i, new_j, True
    return None, None, False

arr = np.arange(16).reshape((4, 4))
print arr
print_spiral(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
0
1
2
3
7
11
15
14
13
12
8
4
5
6
10
9


In [3]:
from math import sqrt

def prime_factors(n):
    num = []
    #add 2 to list or prime factors and remove all even numbers(like sieve of ertosthenes)
    while (n%2 == 0):
        num.append(2)
        n /= 2
        
    #divide by odd numbers and remove all of their multiples increment by 2 if no perfectlly devides add it
    for i in xrange(3, int(sqrt(n))+1, 2):
        while (n%i == 0):
            num.append(i)
            n /= i

    #if no is > 2 i.e no is a prime number that is only divisble by itself add it
    if n>2:
        num.append(n)
        
    print num
    
prime_factors(15)

[3, 5]


In [4]:
def get_words():
    f = open('/usr/share/dict/words')
    words = [word.strip() for word in f]
    return words

def find_word(word, start, end):
    if start >= end:
        return -1
    mid = (start + end) / 2
    mid_word = words[mid].lower()
    print start, mid, end, mid_word
    if word == mid_word:
        return word
    elif word < mid_word:
        return find_word(word, start, mid)
    else:
        return find_word(word, mid + 1, end)

words = get_words()
print find_word('alphabet', 0, len(words))

0 117943 235886 modifier
0 58971 117943 eagle
0 29485 58971 canarian
0 14742 29485 astheny
0 7371 14742 amylamine
0 3685 7371 afterpart
3686 5528 7371 alleviator
5529 6450 7371 amblychromatic
5529 5989 6450 alruna
5529 5759 5989 alluvion
5760 5874 5989 aloewood
5875 5932 5989 alpestrian
5933 5961 5989 alphorn
5933 5947 5961 alphard
5933 5940 5947 alphabetics
5933 5936 5940 alphabetarian
5933 5934 5936 alpha
5935 5935 5936 alphabet
alphabet


In [5]:
print 'hello' > 'collectional '

True


In [2]:
class Node:
    data = None
    left = right = None

    def __init__(self, data, left=None, right=None):
        self.data = data
        self.left = left
        self.right = right
        return
    
    def __str__(self):
        return str('node: %s' % self.data)
    
node = Node(1)
node.left, node.right = Node(2, Node(0), Node(1)), Node(5, Node(-1), Node(-2))

In [ ]:
#       1(5)
#   2(3)    5(2) 
# 0  1   -1   -2

def max_subtree(node, max_seen=None, max_node=None):
    if node.left is None and node.right is None:
        return node.data
    
    left_sum = max_subtree(node.left, max_seen, max_node) if node.left else 0
    right_sum = max_subtree(node.right, max_seen, max_node) if node.right else 0
    node_sum = left_sum + right_sum + node.data
    
    if node_sum > max_seen:
        max_seen = node_sum
        max_node = node
        
    print max_seen, max_node.data
    return node_sum

max_subtree(node)
print max_seen, max_node

In [4]:
def get_num_nodes(node, num_edges=0):
    if node is None:
        return num_edges
    num_edges += 1
    for child in [node.left, node.right]:
        num_edges += get_num_nodes(child)
    return num_edges

get_num_nodes(node) 

7

In [6]:
a = np.array([[1, .75], [.75, 1]])
b = np.array([1, 1])
print np.linalg.solve(a, b)

[ 0.57142857  0.57142857]
